# Generated by Django 5.1.15 on 2026-06-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='Short caption / alt text.', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Photo.', upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL — used only if no file is uploaded above.', max_length=500)),
                ('show_on_home', models.BooleanField(default=False, help_text="Also show this photo in the 'Glimpses from the Past' strip on the home page.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Partner / school name (also used as the image's alt text).", max_length=120)),
                ('image', models.ImageField(blank=True, help_text='Logo image.', upload_to='partners/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL — used only if no file is uploaded above.', max_length=500)),
                ('link', models.URLField(blank=True, help_text='Optional website to open when the logo is clicked.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
            ],
            options={
                'verbose_name': 'Partner Logo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo shown in the navbar (a PNG with a transparent background works best).', upload_to='site/')),
                ('hero_background', models.ImageField(blank=True, help_text='Background image behind the home hero video.', upload_to='site/')),
                ('hero_background_url', models.URLField(blank=True, help_text='External image URL — used only if no file is uploaded above.', max_length=500)),
                ('hero_video', models.FileField(blank=True, help_text='Home hero video (MP4).', upload_to='site/')),
                ('hero_title', models.CharField(default='Wisbees Business Carnival', help_text='Big title shown on the home hero.', max_length=120)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Optional one-line subtitle under the hero title. Leave blank to keep the styled default text.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home_column', 'Home page — scrolling columns'), ('parent', 'Testimonials page — Parents'), ('school', 'Testimonials page — Schools')], default='home_column', max_length=20)),
                ('quote', models.TextField(help_text='The testimonial text.')),
                ('name', models.CharField(help_text="Who said it (e.g. 'Parent of Arnav — Sanskriti School').", max_length=160)),
                ('role', models.CharField(blank=True, help_text='Optional role / subtitle (shown on the home page columns).', max_length=160)),
                ('photo', models.ImageField(blank=True, help_text='Avatar photo.', upload_to='testimonials/')),
                ('photo_url', models.URLField(blank=True, help_text='External image URL — used only if no file is uploaded above.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home_why', "Home page — 'Why WBC' video"), ('gallery', 'Gallery page — Videos tab'), ('founder', 'Founder Videos page'), ('student', 'Testimonials page — Student videos')], default='gallery', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(help_text="Just the YouTube video ID, e.g. 'dD-97KGGfqA' (the part after watch?v=).", max_length=40)),
                ('subtitle', models.CharField(blank=True, help_text="Optional subtitle (e.g. the student's name on the Testimonials page).", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
            ],
            options={
                'verbose_name': 'Video',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
