# Generated by Django 5.1.15 on 2026-06-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_seed_sponsorship_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="countdown_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Target date & time the top announcement banner counts down to. Change this any time to reset the countdown. Leave blank to use the site default.",
                null=True,
            ),
        ),
    ]
