# Generated by Django 5.1.15 on 2026-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_siteconfig_countdown_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="countdown_location",
            field=models.CharField(
                blank=True,
                help_text="City where the event is happening, e.g. 'Pune'. Shown in the top banner as 'Coming to <city> in …'. Leave blank to use the site default.",
                max_length=80,
            ),
        ),
    ]
