# Generated by Django 5.1.15 on 2026-06-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_siteconfig_countdown_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="contact_address",
            field=models.TextField(
                blank=True,
                help_text="Full postal address shown on the Contact Us page.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_email",
            field=models.EmailField(
                blank=True, help_text="Public contact email address.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_mobile",
            field=models.CharField(
                blank=True,
                help_text="Phone number, e.g. +91 98765 43210.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_whatsapp",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number, e.g. +91 98765 43210. Used to build a wa.me chat link.",
                max_length=40,
            ),
        ),
    ]
