# Generated by Django 5.1.15 on 2026-06-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0006_siteconfig_contact_address_siteconfig_contact_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EcosystemProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name, e.g. 'Buzz by Wisbees'.",
                        max_length=120,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="One-line description shown under the product name.",
                        max_length=200,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Optional small note, e.g. '(Coming Soon)'.",
                        max_length=80,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="URL opened when the product is clicked. Leave blank for '#'.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Untick to hide without deleting."
                    ),
                ),
            ],
            options={
                "verbose_name": "Ecosystem Product",
                "ordering": ["order", "id"],
            },
        ),
    ]
