// Rural unemployment rate per state, in % (PLFS FY2023).
// Edit values here. Keys must match state names in INDIA_MAP.
// Omit a state to mark its rural-unemployment data as unavailable.

export const RURAL_UNEMPLOYMENT: Record<string, number> = {
  'Andhra Pradesh': 3.3,
  'Arunachal Pradesh': 3.9,
  'Assam': 1.5,
  'Bihar': 3.6,
  'Chandigarh': 3.2,
  'Chhattisgarh': 1.4,
  'Delhi': 10.2,
  'Goa': 11.3,
  'Gujarat': 1.4,
  'Haryana': 5.8,
  'Himachal Pradesh': 3.5,
  'Jammu and Kashmir': 3.4,
  'Jharkhand': 0.9,
  'Karnataka': 1.5,
  'Kerala': 6.5,
  'Madhya Pradesh': 0.8,
  'Maharashtra': 2.2,
  'Manipur': 4.5,
  'Meghalaya': 5.0,
  'Mizoram': 1.2,
  'Nagaland': 2.9,
  'Odisha': 3.6,
  'Puducherry': 5.9,
  'Punjab': 6.2,
  'Rajasthan': 3.4,
  'Sikkim': 2.2,
  'Tamil Nadu': 3.8,
  'Telangana': 2.8,
  'Tripura': 1.1,
  'Uttar Pradesh': 1.5,
  'Uttarakhand': 3.9,
  'West Bengal': 1.5,
  'Ladakh': 5.7,
  'Andaman and Nicobar Islands': 6.6,
  'Dadra and Nagar Haveli and Daman and Diu': 4.1,
  'Lakshadweep': 5.6,
};
