// Urban unemployment rate per state, in % (PLFS FY2023).
// Edit values here. Keys must match state names in INDIA_MAP.
// Omit a state to mark its urban-unemployment data as unavailable.

export const URBAN_UNEMPLOYMENT: Record<string, number> = {
  'Andhra Pradesh': 6.5,
  'Arunachal Pradesh': 10.9,
  'Assam': 6.1,
  'Bihar': 7.7,
  'Chandigarh': 4.0,
  'Chhattisgarh': 7.8,
  'Delhi': 1.7,
  'Goa': 8.7,
  'Gujarat': 2.2,
  'Haryana': 6.5,
  'Himachal Pradesh': 14.1,
  'Jammu and Kashmir': 10.2,
  'Jharkhand': 6.3,
  'Karnataka': 4.2,
  'Kerala': 7.6,
  'Madhya Pradesh': 4.8,
  'Maharashtra': 4.6,
  'Manipur': 5.3,
  'Meghalaya': 12.3,
  'Mizoram': 3.5,
  'Nagaland': 8.6,
  'Odisha': 6.2,
  'Puducherry': 5.4,
  'Punjab': 6.0,
  'Rajasthan': 8.5,
  'Sikkim': 2.2,
  'Tamil Nadu': 5.1,
  'Telangana': 7.8,
  'Tripura': 3.0,
  'Uttar Pradesh': 6.5,
  'Uttarakhand': 6.6,
  'West Bengal': 3.8,
  'Ladakh': 10.8,
  'Andaman and Nicobar Islands': 14.0,
  'Dadra and Nagar Haveli and Daman and Diu': 1.4,
  'Lakshadweep': 12.8,
};
